import { housesDetailModel } from './houses-detailModel'

export const housesDetail: housesDetailModel[] = [
  {
    parking: '۲',
    bathroom: '۲',
    storage: '۳',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'جنوبی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    room: '۳',
    floor: '۱',
    houseId: '1',
  },
  {
    parking: '۳',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: '۵ سال',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت، نگهبان',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    room: '۲',
    floor: '۳',
    houseId: '2',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۱۲۴',
    saves: '۴۴',
    room: '۳',
    floor: '۱',
    houseId: '3',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'چوب',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری',
    visitingHours: ['۹', '۱۰'],
    views: '۲۲',
    saves: '۶',
    room: '۳',
    floor: '۲',
    houseId: '4',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'پارکت',
    heatingSystem: 'نوساز',
    age: '۱۰ سال',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۸', '۸'],
    views: '۴۴۳',
    saves: '۳۹',
    room: '۴',
    floor: '۱',
    houseId: '5',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۴۳',
    saves: '۱۲۱',
    room: '۳',
    floor: '۳',
    houseId: '6',
  },
  {
    parking: '۲',
    bathroom: '۳',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'جنوبی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۶۴۸',
    saves: '۳۲۳',
    room: '۳',
    floor: '۶',
    houseId: '7',
  },
  {
    parking: '۲',
    bathroom: '۴',
    storage: '۵',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۸', '۷'],
    views: '۳۲۱۲',
    saves: '۳۱۲',
    room: '۴',
    floor: '۱',
    houseId: '8',
  },

  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۰', '۷'],
    views: '۱۲۴۸',
    saves: '۸۱۲',
    room: '۴',
    floor: '۸',
    houseId: '9',
  },
  {
    parking: '۴',
    bathroom: '۱',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۵',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۲۳',
    saves: '۱',
    room: '۳',
    floor: '۲',
    houseId: '10',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'پارکت',
    heatingSystem: 'نوساز',
    age: '۲ سال',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲۳',
    saves: '۸۳',
    room: '۳',
    floor: '۱',
    houseId: '11',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۱۱'],
    views: '۴۳',
    saves: '۸',
    room: '۳',
    floor: '۱',
    houseId: '12',
  },
  {
    parking: '۳',
    bathroom: '۳',
    storage: '۴',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۲', '۷'],
    views: '۴۳۲',
    saves: '۴۳',
    room: '۳',
    floor: '۴',
    houseId: '13',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'چوب',
    heatingSystem: 'نوساز',
    age: '۳ سال',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۰', '۱۰'],
    views: '۶۷۸',
    saves: '۳۱۲',
    room: '۴',
    floor: '۳',
    houseId: '14',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۷', '۷'],
    views: '۴۲',
    saves: '۱۲',
    room: '۳',
    floor: '۷',
    houseId: '15',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'جنوبی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری',
    visitingHours: ['۸', '۶'],
    views: '۳۴۲۴',
    saves: '۲۳۲',
    room: '۳',
    floor: '۲',
    houseId: '16',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۹۰',
    saves: '۵۳',
    room: '۳',
    floor: '۶',
    houseId: '17',
  },
  {
    parking: '۲',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: '۱۵ سال',
    location: 'غربی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت،‌ لابی،‌ نگهبان',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۸', '۷'],
    views: '۲',
    saves: '۰',
    room: '۲',
    floor: '۶',
    houseId: '18',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۱',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'جنوبی',
    documentType: 'شخصی',
    security: 'ایفون تصویری',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۰', '۹'],
    views: '۳۲',
    saves: '۸',
    room: '۳',
    floor: '۵',
    houseId: '19',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۴۲',
    saves: '۴',
    room: '۳',
    floor: '۱',
    houseId: '20',
  },
  {
    parking: '۱',
    bathroom: '۳',
    storage: '۳',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۵۶',
    saves: '۲۳',
    room: '۳',
    floor: '۳',
    houseId: '21',
  },
  {
    parking: '۱',
    bathroom: '۴',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۰', '۹'],
    views: '۳۳۲',
    saves: '۵۵',
    room: '۴',
    floor: '۸',
    houseId: '22',
  },
  {
    parking: '۰',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۶۷',
    saves: '۴',
    room: '۳',
    floor: '۱',
    houseId: '23',
  },
  {
    parking: '۲',
    bathroom: '۱',
    storage: '۲',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۸'],
    views: '۵۲',
    saves: '۱۰',
    room: '۳',
    floor: '۵',
    houseId: '24',
  },
]
