import { housesModel } from './housesModel'

export const houses: housesModel[] = [
  // Gilan houses
  {
    image: 'house1',
    hoursPosted: '۲',
    area: '110',
    address: 'رشت، خیابان امام خمینی',
    rahnPrice: '600',
    ejarePrice: '30',
    cityId: '1',
    houseId: '1',
  },
  {
    image: 'house1',
    hoursPosted: '۴۶',
    area: '80',
    address: 'رشت، خیابان بهشتی',
    rahnPrice: '400',
    ejarePrice: '20',
    cityId: '1',
    houseId: '2',
  },
  {
    image: 'house1',
    hoursPosted: '۲۳',
    area: '150',
    address: 'رشت، خیابان باقری',
    rahnPrice: '700',
    ejarePrice: '40',
    cityId: '1',
    houseId: '3',
  },
  {
    image: 'house1',
    hoursPosted: '۶۷',
    area: '200',
    address: 'رشت، خیابان شهید رجایی',
    rahnPrice: '800',
    ejarePrice: '50',
    cityId: '1',
    houseId: '4',
  },
  {
    image: 'house1',
    hoursPosted: '۱',
    area: '180',
    address: 'رشت، خیابان مطهری',
    rahnPrice: '750',
    ejarePrice: '45',
    cityId: '1',
    houseId: '5',
  },
  {
    image: 'house1',
    hoursPosted: '۳۲',
    area: '100',
    address: 'رشت، خیابان شهید بهشتی',
    rahnPrice: '550',
    ejarePrice: '25',
    cityId: '1',
    houseId: '6',
  },
  {
    image: 'house1',
    hoursPosted: '۲۳',
    area: '130',
    address: 'رشت، خیابان آیت الله کاشانی',
    rahnPrice: '650',
    ejarePrice: '35',
    cityId: '1',
    houseId: '7',
  },
  {
    image: 'house1',
    hoursPosted: '۳۴',
    area: '90',
    address: 'رشت، خیابان فردوسی',
    rahnPrice: '500',
    ejarePrice: '20',
    cityId: '1',
    houseId: '8',
  },

  // Tehran houses
  {
    image: 'house1',
    hoursPosted: '۳',
    area: '180',
    address: 'تهران، خیابان ولیعصر',
    rahnPrice: '700',
    ejarePrice: '35',
    cityId: '2',
    houseId: '9',
  },
  {
    image: 'house1',
    hoursPosted: '۱۵',
    area: '120',
    address: 'تهران، خیابان جمالزاده',
    rahnPrice: '600',
    ejarePrice: '30',
    cityId: '2',
    houseId: '10',
  },
  {
    image: 'house1',
    hoursPosted: '۴۰',
    area: '160',
    address: 'تهران، خیابان شهید بهشتی',
    rahnPrice: '750',
    ejarePrice: '40',
    cityId: '2',
    houseId: '11',
  },
  {
    image: 'house1',
    hoursPosted: '۲۰',
    area: '200',
    address: 'تهران، خیابان انقلاب',
    rahnPrice: '800',
    ejarePrice: '50',
    cityId: '2',
    houseId: '12',
  },
  {
    image: 'house1',
    hoursPosted: '۱۲',
    area: '150',
    address: 'تهران، خیابان فاطمی',
    rahnPrice: '700',
    ejarePrice: '35',
    cityId: '2',
    houseId: '13',
  },
  {
    image: 'house1',
    hoursPosted: '۱۶',
    area: '170',
    address: 'تهران، خیابان پاسداران',
    rahnPrice: '750',
    ejarePrice: '40',
    cityId: '2',
    houseId: '14',
  },
  {
    image: 'house1',
    hoursPosted: '۲۴',
    area: '190',
    address: 'تهران، خیابان شهید چمران',
    rahnPrice: '780',
    ejarePrice: '45',
    cityId: '2',
    houseId: '15',
  },
  {
    image: 'house1',
    hoursPosted: '۳۰',
    area: '140',
    address: 'تهران، خیابان پیروزی',
    rahnPrice: '680',
    ejarePrice: '35',
    cityId: '2',
    houseId: '16',
  },
  //Fars houses
  {
    image: 'house1',
    hoursPosted: '۱۰',
    area: '180',
    address: 'شیراز، خیابان قصردشت',
    rahnPrice: '700',
    ejarePrice: '35',
    cityId: '3',
    houseId: '17',
  },
  {
    image: 'house1',
    hoursPosted: '۲۰',
    area: '120',
    address: 'شیراز، خیابان مطهری',
    rahnPrice: '600',
    ejarePrice: '30',
    cityId: '3',
    houseId: '18',
  },
  {
    image: 'house1',
    hoursPosted: '۱۵',
    area: '160',
    address: 'شیراز، خیابان استادان',
    rahnPrice: '750',
    ejarePrice: '40',
    cityId: '3',
    houseId: '19',
  },
  {
    image: 'house1',
    hoursPosted: '۲۵',
    area: '200',
    address: 'شیراز، خیابان پارک ساعی',
    rahnPrice: '800',
    ejarePrice: '50',
    cityId: '3',
    houseId: '20',
  },
  {
    image: 'house1',
    hoursPosted: '۱۲',
    area: '150',
    address: 'شیراز، خیابان میرزا کوچک خان',
    rahnPrice: '700',
    ejarePrice: '35',
    cityId: '3',
    houseId: '21',
  },
  {
    image: 'house1',
    hoursPosted: '۲۰',
    area: '170',
    address: 'شیراز، خیابان زند',
    rahnPrice: '750',
    ejarePrice: '40',
    cityId: '3',
    houseId: '22',
  },
  {
    image: 'house1',
    hoursPosted: '۳۰',
    area: '190',
    address: 'شیراز، خیابان امیرکبیر',
    rahnPrice: '780',
    ejarePrice: '45',
    cityId: '3',
    houseId: '23',
  },
  {
    image: 'house1',
    hoursPosted: '۳۵',
    area: '140',
    address: 'شیراز، خیابان سعدی',
    rahnPrice: '680',
    ejarePrice: '35',
    cityId: '3',
    houseId: '24',
  },
]
