import { housesModel } from './housesModel'

export const houses: housesModel[] = [
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '1',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '2',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '3',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '4',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '5',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '6',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '7',
  },
  {
    image: 'house1',
    hoursPosted: '10',
    area: '80',
    address: 'رشت، گلسار، خیابان ۹۸',
    rahnPrice: '500',
    ejarePrice: '15',
    cityId: '1',
    houseId: '8',
  },

  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '9',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '10',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '11',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '12',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '13',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '14',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '15',
  },
  {
    image: 'house1',
    hoursPosted: '3',
    area: '80',
    address: 'تهران صادقیه خیابان ۲۳',
    rahnPrice: '600',
    ejarePrice: '35',
    cityId: '2',
    houseId: '16',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '17',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '18',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '19',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '20',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '21',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '22',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '23',
  },
  {
    image: 'house1',
    hoursPosted: '5',
    area: '220',
    address: 'شیراز، ملوانان، خیابان رسالت',
    rahnPrice: '300',
    ejarePrice: '100',
    cityId: '3',
    houseId: '24',
  },
]
