import { housesDetailModel } from './houses-detailModel'

export const housesDetail: housesDetailModel[] = [
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '1',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '2',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '3',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '4',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '5',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '6',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '7',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '8',
  },

  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '9',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '10',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '11',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '12',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '13',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '14',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '15',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '16',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '17',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '18',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '19',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '20',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '21',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '22',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '23',
  },
  {
    parking: '۱',
    bathroom: '۲',
    storage: '۱',
    bathroomType: 'فرنگی',
    elevator: '۳',
    coolingSystem: 'چیلر',
    floorMaterial: 'سرامیک',
    heatingSystem: 'نوساز',
    age: 'نوساز',
    location: 'شمالی',
    documentType: 'شخصی',
    security: 'ایفون تصویری، درب ضد سرقت',
    otherFeatures: 'کمد دیواری، پنجره UPVC',
    visitingHours: ['۱۱', '۷'],
    views: '۳۲',
    saves: '۸',
    houseId: '24',
  },
]
